### PR TITLE
Deleting default files for CentOS/RedHat and ssl default file

### PR DESCRIPTION
**Pull request by horacimacias**
This is an attempt to solve issues:

https://github.com/geerlingguy/ansible-role-apache/issues/81 https://github.com/geerlingguy/ansible-role-apache/issues/21

In summary the default vhost file variable now holds an array, and there is a variable for ssl vhosts as well.
Looks like the set of default files varies depending on OS and Apache version; perhaps there is a better way to organise the variables.

### CODE REVIEW

**Comment by nuncanada** [comment]
There is a line "Listen 443 https" in ssl.conf that is necessary. You simply delete it, it needs to be present somewhere...

**Comment by horacimacias** [comment]
sorry I'm not sure I follow you.
I don't think I modified any ssl.conf file or removed that Listen line myself on the changes.
Can you please elaborate?

**Comment by nuncanada** [comment]
Apache won't listen to port 443 if ssl.conf is removed, because in
http.conf it only has the Listen 80 directive.

So that line needs to be added somewhere. Maybe Oracle Linux has some
difference to CentOS? But i would guess not.

**Comment by horacimacias** [comment]
the change I'm suggesting is to allow users to configure whether default files should be removed or not.
It's up to you to choose that or not. If you choose to have the role remove the file, it will be removed.
Yes, Listen 443 and anything else on ssl.conf will be deleted, **because you requested that.**
As long as the user of the role has the choice, I don't see that as a problem, do you?

On your "_Apache won't listen to port 443 if ssl.conf is removed, because in
http.conf it only has the Listen 80 directive._"
that's correct; if you don't have Listen 443 then apache won't listen in 443.
That's still a valid apache configuration, isn't it?
I'm not sure I see the problem. if a user wants to setup apache to not listen in 443 then it needs to be able to delete the default ssl.conf file (as this role allows) and apache will still start just fine.

**Comment by LukeHandle** [comment]
I would suggest blanking the file out instead of `absent` as further package updates will replace the missing files.

**Pull request closed without merging**
