### PR TITLE
Includes tasks with_first_found

### PR DESCRIPTION
**Pull request by tterranigma**
PROBLEM
=====
In a playbook, include this role:

```yaml
- hosts: webserver
  tags: web
  any_errors_fatal: true
  gather_facts: false
  become: yes
  roles:
  - ansible-role-apache
```

Then include this playbook in another playbook:

```yaml
- include: another-playbook.yml
- include: web-server.yml
```

If you run ansible with --tags and do not specify the webserver tag, eg:

`ansible-playbook playbook.yml --tags another-tag`

then ansible will fail if running on a machine other than Ubuntu, RedHat, etc. The problem is that include statements in tasks/main.yml contain the variable `ansible_os_family` which will be evaluated even when --tags does not contain the webserver.

### CODE REVIEW

**Comment by geerlingguy** [comment]
@tterranigma - When you mention "then ansible will fail if running on a machine other than Ubuntu, RedHat, etc." — can you give a little more about the use case here? Is there a playbook that's meant to run a lot of different things on a lot of different kinds of servers/OSes?

I may be willing to merge if it fixes a use case that could be considered common, but this adds some rather obtuse `include`s that will add to maintenance overhead/burden because it's not immediately obvious what kind of files would be included in what situations.

**Comment by tterranigma** [comment]
@geerlingguy What happened in my case was this. I am running Arch linux locally. There I run ansible that reads a playbook and provisions some Ubuntu servers on Google Cloud. In the playbook I only include other playbooks that in turn do the actual provisioning. Some of them are run against the local machine (host: localhost) as they have to do with creating firewalls, etc on Google Cloud. 

If I run `ansible -i localhost --tags only-cloud-tasks playbook.yml` what happens is that, with playbook.yml as the entry point, ansible will try to recursively include any file and any role it encounters and then execute only the relevant parts. This results in this role being loaded as well. When it comes to including the setup and configure yml files, since I am running against the localhost, `ansible_os_family` will equal to Arch linux. Ansible will fail as there is no file setup-Arch-linux.yml. 

I am running the latest ansible from git, 2.4.

**Comment by tterranigma** [comment]
@geerlingguy Have you managed to find some time to look at this? Were you able to reproduce? Do you need more info from me?

**Comment by tterranigma** [comment]
Personally, I solved the issue including this role with the `include_role` directive. 

Relevant ansible issue: https://github.com/ansible/ansible/issues/37849

**Pull request closed without merging**
