### PR TITLE
Run multi-platform tests on Travis-CI using Docker

### PR DESCRIPTION
**Pull request by bertvv**
This PR replaces the current test configuration for Travis-CI with a new one that will create a Docker container for CentOS and Ubuntu, and run the test playbook on each one. For an example of the result, see <https://travis-ci.org/bertvv/ansible-role-apache/builds/96439547>

What could be added is running black box system/acceptance tests from the host system (i.e. the Travis-CI VM), e.g. trying to access the website that runs on the container with `curl`. This is left as an exercise to the upstream maintainer... ;-)

### CODE REVIEW

**Comment by geerlingguy** [comment]
One thing that seems to still need fixing—it looks like Apache was already installed inside both containers, meaning the role didn't install it and parts of the role weren't tested as thoroughly as a result (e.g. [centos](https://travis-ci.org/geerlingguy/ansible-role-apache/jobs/96441320#L892) and [ubuntu](https://travis-ci.org/geerlingguy/ansible-role-apache/jobs/96441321). As a preliminary step, we should uninstall Apache inside the container and delete any existing configuration (e.g. `--purge` etc.) prior to running the role (via the Dockerfile, I presume). I'm slightly surprised that Apache's already installed on the minimal CentOS docker containers, but I guess it's considered one of the essential packages?

This is really awesome, and I think this will be the way forward for testing on Travis! One tiny annoying thing is that all the output loses it's color (e.g. yellow for changed, green for OK)... don't know how simple it would be to get that color to make it through from Docker run -> travis output, though. And that's definitely not a blocker to getting this PR accepted, just a nice to have!

**Comment by bertvv** [comment]
I'm going to check what's going on there. Apache should not be installed before applying the role. The containers don't even have sshd, so Apache should also not be there...

**Comment by bertvv** [comment]
As far as I can tell, Apache is in fact installed by your role. An excerpt from the log (for centos):

```
TASK: [geerlingguy.apache | Ensure Apache is installed.] ********************** 
changed: [localhost] => (item=httpd,httpd-devel,mod_ssl,openssh)
```

As for the colors, they are also missing when I run the rests locally.

**Comment by bertvv** [comment]
Option `-t` should preserve the color output. Will try this out, but not today... ;)

**Comment by geerlingguy** [comment]
Oh, haha! Sorry about that, I was looking at the _second_ one, which is the one for Debian (which is, rightly, skipped). I'm going to give one more close inspection then I think this will be mergeable as-is!

We can work on the coloring later.

**Comment by bertvv** [comment]
It's not yet mergeable, but I'll fix it. I realized earlier tonight that requirements.yml installs the latest stable release published on Galaxy instead of HEAD. Chances are those tests will all pass... ;)

**Comment by geerlingguy** [comment]
Ha, quite true, since you're using requirements.yml to install the role.

**Comment by bertvv** [comment]
Ok, I fixed it. Sorry about that! The changes have some added benefit.

* the test code is not put in the Docker container at build time, but when it's run. As a consequence, you could publish the test containers on Docker hub and reuse them instead of building them on-the-fly
* I renamed the role in the test script "role_under_test" so the code can be used as-is in all your roles. The only thing to be changed is the "vars:" section.
* The output is now colorized

Also, check out https://github.com/weldpua2008/ansible-apache/. He also uses this technique for testing his Ansible roles on Travis using Docker.

**Comment by geerlingguy** [comment]
Mind. Blown. I'll definitely be switching _all_ my roles soon, hopefully sooner rather than later!

**Comment by bertvv** [comment]
Thanks! ;-) I'm quite pleased with the results myself, and I learned a *lot* the last few days.

I just published a write-up on my blog: https://bertvv.github.io/notes-to-self/2015/12/13/testing-ansible-roles-with-travis-ci-part-2-multi-platform-tests/

**Comment by xenithorb** [comment]
One thing to note here for Ubuntu 14.04 (upstart) based containers, are that the [default ubuntu dockerfile build](https://github.com/tianon/docker-brew-ubuntu-core/blob/3485528d76452eff9e7d3b3f222bd21a966659a5/trusty/Dockerfile#L13-#L16) masks (through dpkg-divert) the `initctl` command with a script that basically contains `exit 0` and thus if you playbook starts a service, it's not _actually_ started, but ansible won't complain because the command always exits successfully. 

I'm not super familiar with docker, but tried reversing this in my downstream Dockerfile that I'm using with travis by adding:

```dockerfile
RUN dpkg-divert --local --rename --remove /sbin/initctl
```

but that caused a "not allowed" error. I then tried replacing that with 

```docker
RUN mv /sbin/initctl.distrib /sbin/initctl
```
And that worked as far as actually getting the service started (I can tell because part of my playbook actually checks for connectivity). **But**, it then causes the travis task to hang and fails eventually when it reaches the timeout limit. Not sure how to fix that. 

Ultimately it seems that the way forward might be in not using official containers, but rather ones that are built for more complete system testing versus the usual "one task per container" methodology that you find throughout docker.

**Pull request merged**
