### PR TITLE
Solaris support

### PR DESCRIPTION
**Pull request by liquidat**
Add Solaris support. The file meta/main.yml now contains the proper platform definition as requested, Ansible Galaxy now supports that platform according to issue https://github.com/ansible/galaxy-issues/issues/102

### CODE REVIEW

**Comment by geerlingguy** [comment]
The feature is still in internal testing at Ansible (it won't be released until that issue is closed). But I'll watch that issue and merge this after that's done. Thanks!

**Comment by liquidat** [comment]
I've added Suse as well. So if you add this pull request I can push another one for Suse right behind.

**Comment by geerlingguy** [comment]
Thanks! Things seem to work fine for me here.

**Comment by geerlingguy** [comment]
@liquidat - Can you also add the supported Suse versions in the meta/main.yml file in a separate PR?

**Comment by liquidat** [comment]
Sorry, forgot that again. I sent another pull request.

**Comment by geerlingguy** [comment]
Thanks!

**Pull request merged**
