### PR TITLE
use apache2_module to handle modules

### LINKED ISSUE #139: apache_mods_enabled ignores dependencies (eg for mod_ssl)
My experience is based on a Debian/Ubuntu setup.

The naive expectation of the `apache_mods_enabled` configuration variable is that it will function similar to a2enmod, which will typically symlink modules to enable them.

Problem is that for more complex modules this is not sufficient.

In my specific case the ssl module fails to properly load when specifying it as ssl.load like in the example.

a2enmod would also evaluate dependencies listed in ssl.load, resulting in enabling additional modules like socache_shmcb. It would also link the ssl.conf file which brings in required configuration settings.

```
# Depends: setenvif mime socache_shmcb
LoadModule ssl_module /usr/lib/apache2/modules/mod_ssl.so
```

My expectation would be that the role internally use `apache2_module` to enable the roles which takes care of the mentioned specialties.

### PR DESCRIPTION
**Pull request by stephankn**
use ansible apache2_module to handle management of modules. This respects the declared dependencies of modules as it will internally use a2enmod.

fixes #139

### CODE REVIEW

**Comment by stephankn** [comment]
`apache_mods_enabled` list has to include now only the module name This makes it was well more consistent with the documentation stating "_Which Apache mods to enable or disable_". Stating filenames was likely a workaround for the apache2_module module not being available in the past.

Tests currently fails due to the test stating file-names instead of module names.

**Comment by stephankn** [comment]
Is there any more input needed or other changes to get this merged?

**Comment by geerlingguy** [comment]
This looks good, but note that this is a breaking change, since anyone who's overridden `apache_mods_enabled` will need to update the list to remove `.load` from all entries, therefore merging this should trigger a major version bump so people know to update their playbooks and not blindly update.

I would like to merge this, I will just need a little time to choose when to make the breaking change (I have a lot of playbooks that depend on this role and I want to make sure they all work fine so I don't end up with a lot of support tickets after the new release :)

**Comment by stephankn** [comment]
Be aware that using the `apache_mods_enabled` variable and placing module files there is likely breaking the setup/not working, as dependencies are not respected. See #139 for details. As I wanted to enable ssl and not mess around with the internal dependencies of that module I would prefer to leave that dependency handling to Apache, also as it could change with a new release and that would then break my playbooks when hard-coding the internal dependencies there.

**Comment by stephankn** [comment]
I added some filtering to convert the old legacy statement `mod-name.load` into the module name `mod-name`. This should allow you to integrate the change without breaking existing configurations. The additional jinja filter is quite a low overhead and could be removed some versions into the future, once all old configurations had been adjusted (or leave it in).

**Pull request closed without merging**
