### PR TITLE
Allow other configs in conf file

### PR DESCRIPTION
**Pull request by solomongifford**
This PR adds a new variable (defaulted to empty) that allows for further configuration of the apache conf file.  The use case of turning the ServerSignature to Off is the most obvious, but other changes can also be made as well.

```
apache_configuration_items: []
#  - regexp: "^ServerSignature "
#    line: "ServerSignature Off"
```

### CODE REVIEW

**Comment by geerlingguy** [comment]
@solomongifford  - See related: #56 — would that give you what you need, or do you still think it would be good to have this separately?

**Comment by solomongifford** [comment]
@geerlingguy This issue is for the apache config, where #56 is for the vhosts.  Two separate situations in my opinion.

**Comment by geerlingguy** [comment]
What about syntax-wise: it seems it might be somewhat simpler to do something like:

```
apache_configuration_overrides: |
  # Add lines here to be added to the end of the Apache configuration file.
```

Then would it be possible to add an already-present setting (which is defined earlier in the file), and Apache would use the last-defined copy, or would this throw an error? (I haven't tested, just speculating, as this might be easier to support and use than requiring users to add regexes for each configuration item).

**Comment by solomongifford** [comment]
I can possibly test this tomorrow - however, my ultimate goal is to also control prefork and worker settings, which cannot be done by adding a line at the bottom.   (However, this PR doesn't support that either.) 

Are you open to managing the prefork and worker settings as well?  If so, I can update this PR tomorrow.

**Comment by solomongifford** [comment]
After much thought, searching, and testing...here are the issues as I see them.

It appears that apache directives override previous declarations; however I cannot see this in any official documentation.  However, when doing "curl localhost/server-info" after enabling server-info in apache, duplicate directives appear twice in the list.   Some custom modules actually reverse the order of precedence for their directives.  This leads me against just placing at the bottom of the config. 

Some configuration items can be added to the end, like LoadModule, LogFormat, etc; however, this is not where people expect to find them.

Considering the above and for the very-important sake of readability, I think directives should be edited in place and not appended.  

This PR obviously places a lot of the burden on the module user to know/use regex.  While I think thats ok for an advanced feature, I admit that it does not solve anything that needs to be configured inside a block, such as IfModule, Location, Proxy, VirtualHost, and Directory.

I see three paths forward:
a.) Define a variable apache_httpdconf which would allow the playbook to override all configuration in the role via an OPTIONAL jinja file.

b.) Write a number of tasks that each separately know how to configure worker, prefork, LoadModule, etc. and then define a large (and potentially expanding) list of variables that can be overriden in the pattern of apache_listen_port (each config gets its own variable).

c.) Go the route of THIS PR which allows the playbook to override most configuration with regex and also provide a mechanism for managing worker and prefork.

I prefer a or c - and after the considerations today I'm leaning towards option a. I'll update this PR shortly.

**Comment by geerlingguy** [comment]
Option A would be nice, if it's simple enough to document how someone could do it (e.g. here's the example, copy it into your playbook and override as you see fit).

**Comment by solomongifford** [comment]
Ok, this is updated to use Option A.

**Comment by geerlingguy** [comment]
I'll review in a bit.

**Comment by solomongifford** [comment]
Let me know if you needed anything else.

**Comment by solomongifford** [comment]
Seems this is failing unrelated to PR.  Updated to support more than the single config.

**Comment by kzap** [comment]
this is perfect, why is this not merge :(

**Pull request closed without merging**
