### PR TITLE
Add log files

### PR DESCRIPTION
**Pull request by clopnis**
Hi,

I propose an option to add custom log file on each vhost.

Is tested on Debian GNU/Linux 8.2 (jessie) and CentOS release 6.7.

Let me know if you have question.

Regards,
Cyril

### CODE REVIEW

**Comment by geerlingguy** [comment]
I'm split on whether I want to add this in; it's starting to make the vhosts templating a lot more complicated, and there's already an option to self-manage a vhosts file (outside this role), which might be a better option.

**Comment by geerlingguy** [comment]
I'm split on whether I want to add this in; it's starting to make the vhosts templating a lot more complicated, and there's already an option to self-manage a vhosts file (outside this role), which might be a better option.

**Comment by clopnis** [comment]
Hi,
I understand but I thinks logs is major to be setup-able. And as you can see, isn't a requirement, is optional.
In my idea, we should be able to set lot's of stuff in vhost but only optional.

**Comment by erikmouw** [comment]
I agree with Clopnis, this is a very useful feature.

Yes, you can grep your way through log file to get only the log for the vhost you're interested in, but having the ability to separate log files by Apache is a much used feature (to be honest, I can't remember seeing it **not** used with a vhost setup).

Please merge, this is an optional configuration item, so it won't even break existing installations.

**Pull request closed without merging**
